
package lt.viko.eif.s031900.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://webservice.s031900.eif.viko.lt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://webservice.s031900.eif.viko.lt/", className = "lt.viko.eif.s031900.webservice.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://webservice.s031900.eif.viko.lt/", className = "lt.viko.eif.s031900.webservice.HelloWorldResponse")
    @Action(input = "http://webservice.s031900.eif.viko.lt/MyService/helloWorldRequest", output = "http://webservice.s031900.eif.viko.lt/MyService/helloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns lt.viko.eif.s031900.webservice.Human
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newHuman", targetNamespace = "http://webservice.s031900.eif.viko.lt/", className = "lt.viko.eif.s031900.webservice.NewHuman")
    @ResponseWrapper(localName = "newHumanResponse", targetNamespace = "http://webservice.s031900.eif.viko.lt/", className = "lt.viko.eif.s031900.webservice.NewHumanResponse")
    @Action(input = "http://webservice.s031900.eif.viko.lt/MyService/newHumanRequest", output = "http://webservice.s031900.eif.viko.lt/MyService/newHumanResponse")
    public Human newHuman(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<lt.viko.eif.s031900.webservice.Car>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCars", targetNamespace = "http://webservice.s031900.eif.viko.lt/", className = "lt.viko.eif.s031900.webservice.GetCars")
    @ResponseWrapper(localName = "getCarsResponse", targetNamespace = "http://webservice.s031900.eif.viko.lt/", className = "lt.viko.eif.s031900.webservice.GetCarsResponse")
    @Action(input = "http://webservice.s031900.eif.viko.lt/MyService/getCarsRequest", output = "http://webservice.s031900.eif.viko.lt/MyService/getCarsResponse")
    public List<Car> getCars(
        @WebParam(name = "arg0", targetNamespace = "")
        Human arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns lt.viko.eif.s031900.webservice.Car
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newCar", targetNamespace = "http://webservice.s031900.eif.viko.lt/", className = "lt.viko.eif.s031900.webservice.NewCar")
    @ResponseWrapper(localName = "newCarResponse", targetNamespace = "http://webservice.s031900.eif.viko.lt/", className = "lt.viko.eif.s031900.webservice.NewCarResponse")
    @Action(input = "http://webservice.s031900.eif.viko.lt/MyService/newCarRequest", output = "http://webservice.s031900.eif.viko.lt/MyService/newCarResponse")
    public Car newCar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
